Update yaml

diff --git a/.github/workflows/unit_test.yaml b/.github/workflows/unit_test.yaml
--- a/.github/workflows/unit_test.yaml
+++ b/.github/workflows/unit_test.yaml
@@ -1,26 +1,66 @@
-name: AudioGPT Tests
+# name: AudioGPT Tests
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+# on:
+#   push:
+#     branches: [ main ]
+#   pull_request:
+#     branches: [ main ]
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v2
+#     - name: Setup JDK
+#       uses: actions/setup-java@v1
+#       with:
+#         java-version: '11'
+#     - name: Setup Gradle
+#       uses: gradle/setup-gradle@v1
+#       with:
+#         gradle-version: '7.0'
+#     - name: Build with Gradle
+#       run: gradle build
+#     - name: Run JUnit tests
+#       run: gradle test
+name: Java CI
+
+on: [push]
+
+permissions:
+    contents: read
+    checks: write
+    id-token: write
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-    - name: Setup JDK
-      uses: actions/setup-java@v1
-      with:
-        java-version: '11'
-    - name: Setup Gradle
-      uses: gradle/setup-gradle@v1
-      with:
-        gradle-version: '7.0'
-    - name: Build with Gradle
-      run: gradle build
-    - name: Run JUnit tests
-      run: gradle test
+      - uses: actions/checkout@v3
+
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '11'
+
+      - name: Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@v1
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+
+      # build everything (includes running unit tests)
+      - name: Execute Gradle build
+        run: ./gradlew build
+
+      # report the results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          detailed_summary: true # display detailed summary of the report
+          include_passed: true # include passed tests in the results table
